title: Testing utilities for Relaynet implementations in JavaScript

markdown: kramdown

baseurl: /relaynet-testing-js
destination: ../build/docs
remote_theme: pmarsceill/just-the-docs@v0.2.8

search_enabled: false

exclude:
  - Gemfile
  - vendor
